before_script:
  - apt-get update -qq && apt-get install -y -qq python cmake python-dev libblas-dev liblapacke-dev libatlas-base-dev libatlas-dev gcc libgfortran3 libgcc1 libgcc-4.9-dev gfortran python-pip openmpi-bin libopenmpi-dev libhdf5-openmpi-dev python-numpy python-scipy python-pyopencl python-scitools libfftw3-dev libfftw3-mpi-dev python-pytest
  - pip install --upgrade pip
  - pip install --upgrade setuptools
  - pip install mako
  - pip install cython
  - pip install mpi4py
  - pip install sphinx
  - pip install wheel
  - wget https://pypi.python.org/packages/22/82/64dada5382a60471f85f16eb7d01cc1a9620aea855cd665609adf6fdbb0d/h5py-2.6.0.tar.gz
  - tar -zxvf h5py-2.6.0.tar.gz
  - cd h5py-2.6.0
  - export CC=mpicc
  - python setup.py configure --mpi --hdf5=/usr/
  - python setup.py install
  - cd ..

build_job:
  stage: build
  script:
    - mkdir build/
    - cd build
    - cmake -D CMAKE_BUILD_TYPE=Debug -DWITH_LIB_CXX=OFF ..
    - make

test_job:
   stage: test
   script:
    - make test

