before_script:
  - apt-get update -qq && apt-get install -y -qq python


build:
  script:
    - mkdir build/
    - cd build
    - cmake -D CMAKE_BUILD_TYPE=Debug -DWITH_LIB_CXX=OFF ..
    - make
    - make test

