before_install:
	- sudo apt-get update -qq
	- sudo apt-get install -qq python cmake python-dev libblas-dev liblapacke-dev libatlas-base-dev libatlas-dev gcc libgfortran3 libgcc1 libgcc-4.9-dev gfortran python-pip openmpi-bin libopenmpi-dev libhdf5-openmpi-dev python-numpy python-scipy python-pyopencl python-scitools libfftw3-dev libfftw3-mpi-dev python-pytest


language: python
python:
  - "2.7"
# command to install dependencies
install:
	- sudo pip install --upgrade pip
	- sudo pip install --upgrade setuptools
	- sudo pip install mako
	- sudo pip install cython
	- sudo pip install mpi4py
	- sudo pip install sphinx
	- sudo pip install wheel
	- wget https://pypi.python.org/packages/22/82/64dada5382a60471f85f16eb7d01cc1a9620aea855cd665609adf6fdbb0d/h5py-2.6.0.tar.gz
	- tar -zxvf h5py-2.6.0.tar.gz
	- cd h5py-2.6.0
	- export CC=mpicc
	- python setup.py configure --mpi --hdf5=/usr/
	- python setup.py install
	- cd ..
# command to run tests
script:
	- mkdir build/
	- cd build
	- cmake -D CMAKE_BUILD_TYPE=Debug -DWITH_LIB_CXX=OFF ..
	- make
